- name: Get data from devices
  hosts: test
  connection: local
  gather_facts: False

  tasks: 

   - name:  Get CDP neighbors
     ntc_show_command:
       connection: ssh 
       platform: cisco_ios_ssh
       template_dir: "/usr/lib/python2.7/dist-packages/ansible/modules/extras/ntc-ansible/ntc-templates/templates"
       command: "show cdp neighbors detail"
       host: "{{inventory_hostname}}"
       username: "{{username}}"
       password: "{{password}}"
     register: cdp

   - debug: var=cdp

   - name: Update Interface descriptions
     ntc_config_command:
       connection: ssh
       platform: cisco_ios_ssh
       commands:
       - interface {{item.local_port}}
       - description {{item.destination_host|lower}} {{item.remote_port}}
       host: "{{inventory_hostname}}"
       username: "{{username}}"
       password: "{{password}}"
     when: 
     - "'Phone' not in item.platform"
     - "'Meraki' not in item.platform" 
     with_items: "{{cdp.response}}"
